### PR TITLE
Add CustomStringConvertible `var deepDescription: String`

### PR DESCRIPTION
**Pull request by mhuusko5**
Implements  #1

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks so much @mhuusko5 ! 🎉 

Do you mind adding a couple of tests? 

Using at least what you had in the comment in #1 would be good. 😊

**Comment by jessesquires** [comment]
I'll take care of the tests. 😄 

Thanks again @mhuusko5 ! 👍

**Comment by mhuusko5** [comment]
Sorry about the delay. Busy busy busy. Happy to do the tests, but I imagine you'll get to them first.

**Comment by jessesquires** [comment]
@mhuusko5 no worries! 😄 I added a few, but more are always welcome 😊

**Pull request merged**
