### PR TITLE
Fix an issue with deepUnwrap unconditionally returning nil

### PR DESCRIPTION
**Pull request by broadwaylamb**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).

### CODE REVIEW

**Review by jessesquires — APPROVED** [review]
Looks awesome! 🎉 

Thanks @broadwaylamb ! 💯

**Comment by jessesquires** [comment]
Oh, we'll also need:
- update podspec version number
- update xcode proj version number

😄

**Comment by broadwaylamb** [comment]
@jessesquires by the way, I'm curious why we need to run CI on so many platforms despite the fact that the project doesn't contain any platform-specific code? Why not test it only in macOS and Linux + `pod lib lint`? That would make CI faster.

**Comment by jessesquires** [comment]
@broadwaylamb Ha, good point 😄 

I just dumped my basic travis template that I use for all projects.

I guess we could reduce it, but since it's already setup, we might as well keep it.

**Pull request merged**
